name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ZMK firmware
        run: west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=path/to/config
